### ISSUE TITLE
Add Python 3.13 support

### ISSUE THREAD

**Issue by rtibbles** [learningequality/le-utils#142]
```[tasklist]
### Tasks
- [x] Add support for the as yet unreleased Python 3.13
- [x] Add to CI version matrix
- [x] Ensure all tests pass
- [x] Upgrade version for release
```
